development:
  adapter: postgresql
  encoding: unicode
  database: ktrow_development
  username: kara
  host: localhost
  password:
  pool: 5
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: unicode
  database: ktrow_production
  pool: 5
  username: postgres
  password:
  min_messages: WARNING
